Traceback (most recent call last):
  File "s:/Documents/GitHub/ATBS/Chapter_10/tracebackExample.py", line 9, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
